# Set some aliases for easy NixOS package development.
NIXPKGS_LOCAL="/home/auntieneo/code/nixpkgs"
alias nix-build-local='nix-build $NIXPKGS_LOCAL'
alias nbl='nix-build-local'
alias nix-env-local='nix-env -f $NIXPKGS_LOCAL'
alias nel='nix-env-local'
alias nix-shell-local='nix-shell $NIXPKGS_LOCAL'  # FIXME: prevent nix-shell from changing the prompt to green
alias nsl='nix-shell-local'

source $HOME/.bashrc
