if [ -f $HOME/.aliases ]; then
  source $HOME/.aliases
fi

if [ -f $HOME/.common ]; then
  source $HOME/.common
fi

# Set the prompt to Arch Linux's default user prompt.
if [ "$UID" -ne 0 ]; then
  PS1='[\u@\h \W]\$ '
fi
