" change movement keys to dvorak
noremap t j
noremap n k
noremap s l
" and remap the keys that were displaced
noremap j t
noremap k n
noremap l s

" remap screen line based movement keys to dvorak
noremap gt gj
noremap gn gk

" remap window movement keys to dvorak
" displaces the back 'till command, which I don't know what it does
noremap T <C-w><C-j>
" displaces the prev(find) command, which is important
noremap N <C-w><C-k>
" displaces the screen-top command, which is worthless
noremap H <C-w><C-h>
" displaces the subst line command, which is important
noremap S <C-w><C-l>
" remap keys that were displaced
" displaces the help command, which is worthless
noremap K N
" displaces the screen bottom command, which is worthless
noremap L S

" map some tab navigation keys
nmap <C-H> :tabprevious<CR>
nmap <C-S> :tabnext<CR>

" Vim is a piece of shit when it comes to failing gracefully, so disable these for now.
"" YCM key bindings (tab binding is added later with hacks below)
"let g:ycm_key_list_select_completion = ['<C-t>', '<Down>']
"let g:ycm_key_list_previous_completion = ['<C-n>', '<Up>']
"
"" UltiSnips key bindings
"" FIXME: none of my terminals support shift+tab or ctrl+tab
"" FIXME: JumpBackward isn't working at all
"let g:UltiSnipsExpandTrigger = "<tab>"
"let g:UltiSnipsJumpForwardTrigger = "<tab>"
"let g:UltiSnipsJumpBackwardTrigger = "<C-p>"
"let g:UltiSnipsListSnippets = "<C-u>"
"
"" Some hacks to make UltiSnips play with YCM
"" from <http://stackoverflow.com/a/21979915>
"function! g:UltiSnips_Complete()
"  call UltiSnips#ExpandSnippetOrJump()
"  if g:ulti_expand_or_jump_res == 0
"    if pumvisible()
"      return "\<Down>"
"    else
"      return "\<tab>"
"    endif
"  endif
"  return ""
"endfunction
"au BufEnter * exec "inoremap <silent> " . g:UltiSnipsJumpForwardTrigger . " <C-R>=g:UltiSnips_Complete()<cr>"

set tabstop=2
set expandtab
set shiftwidth=2
set smarttab
set cindent
set formatoptions=rolq

set backspace=2

set laststatus=2

com -range=% Csort <line1>,<line2>sort i r /\<\w*(.\{-})/  " sort C function prototypes

"setlocal spell spelllang=en_us  " turn on spell checking

" Make file tab completion behave more like bash
set wildmode=list:longest

" line number information displayed in the status bar
set ruler

syntax on
colorscheme desert
